/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rpsproject;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.rpsproject.GameLogic.Picks;

/**
 *
 * @author ruka
 */
public class GameJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GameJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gamePanel = new javax.swing.JPanel();
        scoorePanel = new javax.swing.JPanel();
        playerLabel = new javax.swing.JLabel();
        playerScooreLabel = new javax.swing.JLabel();
        separatorLabel = new javax.swing.JLabel();
        opponenetScooreLabel = new javax.swing.JLabel();
        opponentLabel = new javax.swing.JLabel();
        PlayerPanel = new javax.swing.JPanel();
        shownPickImageLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        OptionHolderPanel = new javax.swing.JPanel();
        rockButton = new javax.swing.JButton();
        paperButton = new javax.swing.JButton();
        scissorsButton = new javax.swing.JButton();
        showPickTextLabel = new javax.swing.JLabel();
        opponentPanel = new javax.swing.JPanel();
        opponentPick = new javax.swing.JLabel();
        messagePanel = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        gameMenuOption = new javax.swing.JMenu();
        botGameMenuItem = new javax.swing.JMenuItem();
        onlineMenuItem = new javax.swing.JMenuItem();
        exitGameMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playerLabel.setFont(new java.awt.Font("Liberation Sans", 1, 40)); // NOI18N
        playerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        playerLabel.setText("Player ");

        playerScooreLabel.setFont(new java.awt.Font("Liberation Sans", 1, 40)); // NOI18N
        playerScooreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerScooreLabel.setText("0");

        separatorLabel.setFont(new java.awt.Font("Liberation Sans", 1, 40)); // NOI18N
        separatorLabel.setText("-");

        opponenetScooreLabel.setFont(new java.awt.Font("Liberation Sans", 1, 40)); // NOI18N
        opponenetScooreLabel.setText("0");

        opponentLabel.setFont(new java.awt.Font("Liberation Sans", 1, 40)); // NOI18N
        opponentLabel.setText("Oponent");

        javax.swing.GroupLayout scoorePanelLayout = new javax.swing.GroupLayout(scoorePanel);
        scoorePanel.setLayout(scoorePanelLayout);
        scoorePanelLayout.setHorizontalGroup(
            scoorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoorePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(playerScooreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(separatorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(opponenetScooreLabel)
                .addGap(57, 57, 57)
                .addComponent(opponentLabel)
                .addGap(21, 21, 21))
        );
        scoorePanelLayout.setVerticalGroup(
            scoorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scoorePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scoorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(scoorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(separatorLabel)
                        .addComponent(opponenetScooreLabel)
                        .addComponent(opponentLabel))
                    .addGroup(scoorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(playerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerScooreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        shownPickImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shownPickImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/temp.png"))); // NOI18N

        submitButton.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        rockButton.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        rockButton.setText("Rock");
        rockButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                rockButtonActionPerformed(e);
            }
            
        });

        paperButton.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        paperButton.setText("Paper");
        paperButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                paperButtonActionPerformed(e);
            }
            
        });

        scissorsButton.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        scissorsButton.setText("Scissors");
        scissorsButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                scissorsButtonActionPerformed(e);
            }
            
        });
        

        javax.swing.GroupLayout OptionHolderPanelLayout = new javax.swing.GroupLayout(OptionHolderPanel);
        OptionHolderPanel.setLayout(OptionHolderPanelLayout);
        OptionHolderPanelLayout.setHorizontalGroup(
            OptionHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionHolderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OptionHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scissorsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(rockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paperButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        OptionHolderPanelLayout.setVerticalGroup(
            OptionHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionHolderPanelLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(rockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(paperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scissorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        showPickTextLabel.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        showPickTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showPickTextLabel.setText("?");

        javax.swing.GroupLayout PlayerPanelLayout = new javax.swing.GroupLayout(PlayerPanel);
        PlayerPanel.setLayout(PlayerPanelLayout);
        PlayerPanelLayout.setHorizontalGroup(
            PlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanelLayout.createSequentialGroup()
                .addComponent(OptionHolderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PlayerPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(showPickTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(shownPickImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PlayerPanelLayout.setVerticalGroup(
            PlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shownPickImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPickTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(OptionHolderPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        opponentPick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        opponentPick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/temp.png"))); // NOI18N

        javax.swing.GroupLayout opponentPanelLayout = new javax.swing.GroupLayout(opponentPanel);
        opponentPanel.setLayout(opponentPanelLayout);
        opponentPanelLayout.setHorizontalGroup(
            opponentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opponentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opponentPick, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        opponentPanelLayout.setVerticalGroup(
            opponentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opponentPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(opponentPick, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scoorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addComponent(PlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opponentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scoorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opponentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlayerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        messageLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("Test");

        javax.swing.GroupLayout messagePanelLayout = new javax.swing.GroupLayout(messagePanel);
        messagePanel.setLayout(messagePanelLayout);
        messagePanelLayout.setHorizontalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        messagePanelLayout.setVerticalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messageLabel)
        );

        gameMenuOption.setText("Game");

        botGameMenuItem.setText("Bot Game");
        botGameMenuItem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent arg0) {
                disconectGame();
            }
            
        });
        gameMenuOption.add(botGameMenuItem);

        onlineMenuItem.setText("Find Game");
        onlineMenuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                serchForGameOnline();
            }
        });
        gameMenuOption.add(onlineMenuItem);

        exitGameMenuItem.setText("Exit Game");
        exitGameMenuItem.setToolTipText("");
        exitGameMenuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                exitGame();
            }  
        });
        gameMenuOption.add(exitGameMenuItem);

        menuBar.add(gameMenuOption);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Picks playerPick = Picks.NONE;
    OnlinePlay op = new OnlinePlay();

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        buttonsTurnOff();
        GameLogic.playTurn(playerPick);
    }
    public void buttonsTurnOff(){
        submitButton.setEnabled(false);
        scissorsButton.setEnabled(false);
        rockButton.setEnabled(false);
        paperButton.setEnabled(false);
    }

    public void buttonsTurnOn(){
        submitButton.setEnabled(true);
        scissorsButton.setEnabled(true);
        rockButton.setEnabled(true);
        paperButton.setEnabled(true);
    }

    private void scissorsButtonActionPerformed(ActionEvent e){
        //switch shownPickImageLabel
        playerPick = Picks.SCISSORS;
        showPickTextLabel.setText("Scissors");
    }

    private void rockButtonActionPerformed(ActionEvent e){
        playerPick = Picks.ROCK;
        showPickTextLabel.setText("Rock");
    }

    private void paperButtonActionPerformed(ActionEvent e){
        playerPick = Picks.PAPER;
        showPickTextLabel.setText("Paper");
    }

    public void ChangeLoggerText(String t){
        messageLabel.setText(t);
    }

    public void updateScoores(int playerScoore, int opponentScoore){
        playerScooreLabel.setText(playerScoore + "");
        opponenetScooreLabel.setText(opponentScoore + "");
    }

    private void exitGame() {
        dispose();
    }

    private void serchForGameOnline(){
        System.out.println("connectando");
        op.startConnection();;
        GameLogic.turnOnline(true, op);
    }

    private void disconectGame(){
        op.disconnect();
        GameLogic.turnOnline(false, null);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OptionHolderPanel;
    private javax.swing.JButton paperButton;
    private javax.swing.JPanel PlayerPanel;
    private javax.swing.JButton rockButton;
    private javax.swing.JButton scissorsButton;
    private javax.swing.JMenuItem botGameMenuItem;
    private javax.swing.JMenuItem exitGameMenuItem;
    private javax.swing.JMenu gameMenuOption;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JMenuItem onlineMenuItem;
    private javax.swing.JLabel opponenetScooreLabel;
    private javax.swing.JLabel opponentLabel;
    private javax.swing.JPanel opponentPanel;
    private javax.swing.JLabel opponentPick;
    private javax.swing.JLabel playerLabel;
    private javax.swing.JLabel playerScooreLabel;
    private javax.swing.JPanel scoorePanel;
    private javax.swing.JLabel separatorLabel;
    private javax.swing.JLabel showPickTextLabel;
    private javax.swing.JLabel shownPickImageLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
